# configs/fire_smoke_combined.yaml

path: D:/Master/Updated Work/Proposed Paper/Paper V3_1/FireDetect_Pro_Suite_20250904_1102/Paper_V4_Code/dataset

train: fire_smoke_combined_new/images/train
val: fire_smoke_combined_new/images/val
test: fire_smoke_combined_new/images/test

names:
  0: fire
  1: smoke
